
[workspace]
resolver = "2"
members = ["packages/common/api-builder","packages/common/api-types","packages/common/api-util","packages/common/cache/build","packages/common/cache/result","packages/common/clickhouse-inserter","packages/common/clickhouse-user-query","packages/common/config","packages/common/env","packages/common/error/core","packages/common/error/macros","packages/common/gasoline/core","packages/common/gasoline/macros","packages/common/logs","packages/common/metrics","packages/common/pools","packages/common/runtime","packages/common/service-manager","packages/common/telemetry","packages/common/test-deps","packages/common/test-deps-docker","packages/common/types","packages/common/universaldb","packages/common/universalpubsub","packages/common/util/core","packages/common/util/id","packages/common/versioned-data-util","packages/core/actor-kv","packages/core/api-peer","packages/core/api-public","packages/core/bootstrap","packages/core/dump-openapi","packages/core/guard/core","packages/core/guard/server","packages/core/pegboard-gateway","packages/core/pegboard-runner","packages/core/pegboard-serverless","packages/core/pegboard-tunnel","packages/core/workflow-worker","packages/infra/engine","packages/services/epoxy","packages/services/internal","packages/services/namespace","packages/services/pegboard","sdks/rust/api-full","sdks/rust/bare_gen","sdks/rust/data","sdks/rust/epoxy-protocol","sdks/rust/runner-protocol","sdks/rust/tunnel-protocol","sdks/rust/ups-protocol"]

[workspace.package]
version = "25.7.1"
edition = "2024"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[workspace.dependencies]
anyhow = "1.0.82"
async-channel = "2.1.1"
async-nats = "0.33"
async-stream = "0.3"
async-trait = "0.1"
axum-test = "17"
base64 = "0.22"
bcrypt = "0.13.0"
bytes = "1.6.0"
cjson = "0.1"
colored_json = "5.0.0"
console-subscriber = "0.4"
dirs = "5.0.1"
divan = "0.1.17"
foundationdb-tuple = "0.9.1"
fs_extra = "1.3.0"
futures = "0.3.30"
futures-util = "0.3"
glob = "0.3.1"
governor = "0.6"
heck = "0.5"
hex = "0.4"
http-body = "1.0.0"
http-body-util = "0.1.1"
hyper-tls = "0.5.0"
hyper-tungstenite = "0.17.0"
include_dir = "0.7.4"
indoc = "2.0.5"
itertools = "0.14.0"
json5 = "0.4.1"
lazy_static = "1.4"
libc = "0.2"
lz4_flex = "0.11.3"
maplit = "1.0.2"
md5 = "0.7.0"
once_cell = "1.20.2"
opentelemetry-appender-tracing = "0.28.1"
papaya = "0.2.1"
pest_derive = "2.7"
portpicker = "0.1"
prettyplease = "0.2"
protobuf = "2.28"
quote = "1.0"
rand = "0.8"
regex = "1.4"
rstest = "0.26.1"
rustls-pemfile = "2.2.0"
rustyline = "15.0.0"
serde_bare = "0.5.0"
serde_html_form = "0.2.7"
serde_yaml = "0.9.34"
sha2 = "0.10"
slog = "2.7"
slog-async = "2.8"
slog-term = "2.9"
statrs = "0.18"
tabled = "0.17.0"
tempfile = "3.13.0"
thiserror = "1.0.64"
tokio-cron-scheduler = "0.13.0"
tokio-native-tls = "0.3.1"
tokio-stream = "0.1.15"
tokio-tungstenite = "0.26.0"
tokio-util = "0.7"
tower = "0.5"
tracing = "0.1.40"
tracing-core = "0.1"
tracing-opentelemetry = "0.29"
tracing-slog = "0.2"
vergen = "9.0.4"
reqwest-eventsource = "0.6.0"

[workspace.dependencies.sentry]
version = "0.37.0"
default-features = false
features = ["anyhow","backtrace","contexts","debug-images","panic","reqwest","rustls"]

[workspace.dependencies.windows]
version = "0.58"
features = ["Win32","Win32_Storage","Win32_Storage_FileSystem","Win32_System","Win32_System_Console","Win32_Security"]

[workspace.dependencies.pest]
version = "2.7"

[workspace.dependencies.rocksdb]
version = "0.24"
features = ["multi-threaded-cf"]

[workspace.dependencies.hyper-util]
version = "0.1.10"
features = ["full"]

[workspace.dependencies.rustls]
version = "0.23.25"
default-features = false
features = ["ring","std","logging"]

[workspace.dependencies.tokio-rustls]
version = "0.26.2"
default-features = false
features = ["ring","logging"]

[workspace.dependencies.utoipa]
version = "5.4.0"
features = ["uuid"]

[workspace.dependencies.axum]
version = "0.8"
features = ["http2"]

[workspace.dependencies.axum-extra]
version = "0.10.1"
features = ["query"]

[workspace.dependencies.tower-http]
version = "0.6"
features = ["cors","trace"]

[workspace.dependencies.serde_json]
version = "1.0.128"
features = ["raw_value"]

[workspace.dependencies.nix]
version = "0.30"
default-features = false
features = ["fs","user","signal"]

[workspace.dependencies.chrono]
version = "0.4.38"
features = ["now"]

[workspace.dependencies.clap]
version = "4.3"
features = ["derive"]

[workspace.dependencies.rivet-term]
git = "https://github.com/rivet-gg/rivet-term"
rev = "55e328470b68c557fb9bc8298369f90182d35b6d"

[workspace.dependencies.clickhouse]
version = "0.11.2"
features = ["uuid"]

[workspace.dependencies.config]
version = "0.14.0"
default-features = false
features = ["async","json","yaml"]

[workspace.dependencies.hyper]
version = "0.14"
features = ["server","http1","tcp"]

[workspace.dependencies.indexmap]
version = "2.0"
features = ["serde"]

[workspace.dependencies.ipnet]
version = "2.10.1"
features = ["serde"]

[workspace.dependencies.moka]
version = "0.12"
features = ["future"]

[workspace.dependencies.opentelemetry]
version = "0.28"
features = ["trace","metrics","logs"]

[workspace.dependencies.opentelemetry-otlp]
version = "0.28"
features = ["trace","metrics","logs","grpc-tonic"]

[workspace.dependencies.opentelemetry_sdk]
version = "0.28"
features = ["trace","metrics","logs"]

[workspace.dependencies.opentelemetry-semantic-conventions]
version = "0.28"
features = ["semconv_experimental"]

[workspace.dependencies.opentelemetry-stdout]
version = "0.28.0"
features = ["trace","metrics","logs"]

[workspace.dependencies.proc-macro2]
version = "1.0"
features = ["span-locations"]

[workspace.dependencies.reqwest]
version = "0.12.22"
features = ["json"]

[workspace.dependencies.schemars]
version = "0.8.21"
features = ["url","uuid1"]

[workspace.dependencies.serde]
version = "1.0"
features = ["derive"]

[workspace.dependencies.strum]
version = "0.26.3"
features = ["derive"]

[workspace.dependencies.syn]
version = "2.0"
features = ["full","extra-traits"]

[workspace.dependencies.url]
version = "2.5.4"
features = ["serde"]

[workspace.dependencies.uuid]
version = "1.11.0"
features = ["v4","serde"]

[workspace.dependencies.tokio]
version = "1.44.0"
features = ["full","tracing"]

[workspace.dependencies.tokio-postgres]
version = "0.7"
features = ["with-chrono-0_4"]

[workspace.dependencies.deadpool-postgres]
version = "0.14.1"

[workspace.dependencies.tracing-logfmt]
version = "0.3"
features = ["ansi_logs"]

[workspace.dependencies.tracing-subscriber]
version = "0.3"
default-features = false
features = ["ansi","fmt","json","env-filter"]

[workspace.dependencies.rivet-api-builder]
path = "packages/common/api-builder"

[workspace.dependencies.rivet-api-types]
path = "packages/common/api-types"

[workspace.dependencies.rivet-api-util]
path = "packages/common/api-util"

[workspace.dependencies.rivet-cache]
path = "packages/common/cache/build"

[workspace.dependencies.rivet-cache-result]
path = "packages/common/cache/result"

[workspace.dependencies.clickhouse-inserter]
path = "packages/common/clickhouse-inserter"

[workspace.dependencies.clickhouse-user-query]
path = "packages/common/clickhouse-user-query"

[workspace.dependencies.rivet-config]
path = "packages/common/config"

[workspace.dependencies.rivet-env]
path = "packages/common/env"

[workspace.dependencies.rivet-error]
path = "packages/common/error/core"

[workspace.dependencies.rivet-error-macros]
path = "packages/common/error/macros"

[workspace.dependencies.gas]
package = "gasoline"
path = "packages/common/gasoline/core"

[workspace.dependencies.gasoline]
path = "packages/common/gasoline/core"

[workspace.dependencies.gasoline-macros]
path = "packages/common/gasoline/macros"

[workspace.dependencies.rivet-logs]
path = "packages/common/logs"

[workspace.dependencies.rivet-metrics]
path = "packages/common/metrics"

[workspace.dependencies.rivet-pools]
path = "packages/common/pools"

[workspace.dependencies.rivet-runtime]
path = "packages/common/runtime"

[workspace.dependencies.rivet-service-manager]
path = "packages/common/service-manager"

[workspace.dependencies.rivet-telemetry]
path = "packages/common/telemetry"

[workspace.dependencies.rivet-test-deps]
path = "packages/common/test-deps"

[workspace.dependencies.rivet-test-deps-docker]
path = "packages/common/test-deps-docker"

[workspace.dependencies.rivet-types]
path = "packages/common/types"

[workspace.dependencies.universaldb]
path = "packages/common/universaldb"

[workspace.dependencies.universalpubsub]
path = "packages/common/universalpubsub"

[workspace.dependencies.rivet-util]
path = "packages/common/util/core"

[workspace.dependencies.util]
package = "rivet-util"
path = "packages/common/util/core"

[workspace.dependencies.rivet-util-id]
path = "packages/common/util/id"

[workspace.dependencies.versioned-data-util]
path = "packages/common/versioned-data-util"

[workspace.dependencies.pegboard-actor-kv]
path = "packages/core/actor-kv"

[workspace.dependencies.rivet-api-peer]
path = "packages/core/api-peer"

[workspace.dependencies.rivet-api-public]
path = "packages/core/api-public"

[workspace.dependencies.rivet-bootstrap]
path = "packages/core/bootstrap"

[workspace.dependencies.rivet-dump-openapi]
path = "packages/core/dump-openapi"

[workspace.dependencies.rivet-guard-core]
path = "packages/core/guard/core"

[workspace.dependencies.rivet-guard]
path = "packages/core/guard/server"

[workspace.dependencies.pegboard-gateway]
path = "packages/core/pegboard-gateway"

[workspace.dependencies.pegboard-runner]
path = "packages/core/pegboard-runner"

[workspace.dependencies.pegboard-serverless]
path = "packages/core/pegboard-serverless"

[workspace.dependencies.pegboard-tunnel]
path = "packages/core/pegboard-tunnel"

[workspace.dependencies.rivet-workflow-worker]
path = "packages/core/workflow-worker"

[workspace.dependencies.rivet-engine]
path = "packages/infra/engine"

[workspace.dependencies.epoxy]
path = "packages/services/epoxy"

[workspace.dependencies.internal]
path = "packages/services/internal"

[workspace.dependencies.namespace]
path = "packages/services/namespace"

[workspace.dependencies.pegboard]
path = "packages/services/pegboard"

[workspace.dependencies.rivet-api-full]
path = "sdks/rust/api-full"

[workspace.dependencies.bare_gen]
path = "sdks/rust/bare_gen"

[workspace.dependencies.rivet-data]
path = "sdks/rust/data"

[workspace.dependencies.epoxy-protocol]
path = "sdks/rust/epoxy-protocol"

[workspace.dependencies.rivet-runner-protocol]
path = "sdks/rust/runner-protocol"

[workspace.dependencies.rivet-tunnel-protocol]
path = "sdks/rust/tunnel-protocol"

[workspace.dependencies.rivet-ups-protocol]
path = "sdks/rust/ups-protocol"

[profile.dev]
overflow-checks = false
debug = false
lto = "off"

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = false
lto = "fat"
codegen-units = 1
opt-level = 3
