packages:
  - docker/template
  - frontend
  - scripts/tests
  - scripts/release
  - sdks/typescript/api-full
  - sdks/typescript/runner
  - sdks/typescript/runner-protocol
  - sdks/typescript/test-runner
  - sdks/typescript/tunnel-protocol
  - site
  - frontend/packages/components/
  - frontend/packages/icons/

ignoredBuiltDependencies:
  - '@clerk/shared'
  - '@parcel/watcher'
  - '@sentry/cli'
  - browser-tabs-lock
  - cbor-extract
  - core-js
  - lefthook
  - sharp

onlyBuiltDependencies:
  - '@rivet-gg/icons'
  - esbuild
