[package]
name = "pegboard-gateway"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
futures-util.workspace = true
gas.workspace = true
http-body-util.workspace = true
hyper = "1.6"
hyper-tungstenite.workspace = true
pegboard.workspace = true
rand.workspace = true
rivet-error.workspace = true
rivet-guard-core.workspace = true
rivet-util.workspace = true
thiserror.workspace = true
tokio-tungstenite.workspace = true
tokio.workspace = true
universalpubsub.workspace = true
versioned-data-util.workspace = true
